# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

addons:
  chrome: stable

# PHP version used in first build configuration.
php:
  - 7.2

# Prestashop version used in first build configuration.
env:
  global:
    - PS_VERSION=1.7.3.3 PS_MULTISITE=0 RUN_CODE_COVERAGE=1 RUN_PHPCS=1

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo add-apt-repository -y ppa:ondrej/apache2
  - sudo apt-get update

install:
  - sudo apt-get install apache2 php${TRAVIS_PHP_VERSION} php${TRAVIS_PHP_VERSION}-mysql php${TRAVIS_PHP_VERSION}-mbstring php${TRAVIS_PHP_VERSION}-soap php${TRAVIS_PHP_VERSION}-curl php${TRAVIS_PHP_VERSION}-dom php${TRAVIS_PHP_VERSION}-intl php${TRAVIS_PHP_VERSION}-zip
  - composer install --prefer-dist
  - if [[ $RUN_E2E = "1" ]]; then npm install; fi
  - if [[ $RUN_E2E = "1" ]]; then npm install -g gulp; fi
  - if [[ $RUN_E2E = "1" ]]; then npm install -g gulp-cli; fi
  - sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin/ --filename=composer

before_script:
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - sudo sed -i "172,\$s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf
  - sudo service apache2 restart
  - mysql -u root -e "CREATE USER 'dbadmin'@'localhost' IDENTIFIED BY 'dbpass'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'dbadmin'@'localhost' WITH GRANT OPTION;"
  - sudo chown -R travis:travis /var/www/html
  - bash test/bin/build-test.sh $PS_VERSION true
  - bash build/sync.sh .
  - bash build/travis.sh

script:
  - if [[ $PS_MULTISITE = "0" ]]; then /var/www/html/vendor/phpunit/phpunit/phpunit -c /var/www/html/phpunit.xml -v --debug; fi
  - if [[ $PS_MULTISITE = "1" ]]; then /var/www/html/vendor/phpunit/phpunit/phpunit -c /var/www/html/phpunit-multisite.xml -v --debug; fi
  - if [[ $RUN_PHPCS = "1" ]]; then bash build/phpcs.sh true; fi
  - if [[ $RUN_E2E = "1" ]]; then bash test/bin/run-e2e-test.sh true $PS_MULTISITE; fi

after_script:
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar; fi
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then chmod +x php-coveralls.phar; fi
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then php php-coveralls.phar -x /tmp/coverage.xml --verbose; fi

sudo: required
