# Travis CI Configuration File

language: php

addons:
  chrome: stable

php:
  - 7.0

env:
  global:
    - PS_VERSION=1.7.3.4 PS_MULTISITE=0 RUN_CODE_COVERAGE=1 RUN_PHPCS=1

matrix:
  include:
  - php: 5.6
    env: PS_VERSION=1.6.1.4 PS_MULTISITE=0 RUN_CODE_COVERAGE=0 RUN_PHPCS=0
  - php: 7.0
    env: PS_VERSION=1.7.3.4 PS_MULTISITE=1 RUN_CODE_COVERAGE=0 RUN_PHPCS=0
  - php: 7.0
    env: PS_VERSION=1.7.3.4 PS_MULTISITE=0 RUN_CODE_COVERAGE=1 RUN_PHPCS=1

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo add-apt-repository -y ppa:ondrej/apache2
  - sudo apt-get update

install:
  - sudo apt-get install apache2 php${TRAVIS_PHP_VERSION} php${TRAVIS_PHP_VERSION}-mysql php${TRAVIS_PHP_VERSION}-mbstring php${TRAVIS_PHP_VERSION}-soap php${TRAVIS_PHP_VERSION}-curl php${TRAVIS_PHP_VERSION}-dom php${TRAVIS_PHP_VERSION}-intl php${TRAVIS_PHP_VERSION}-zip php${TRAVIS_PHP_VERSION}-mcrypt
  - composer install --prefer-dist
  - npm install
  - npm install -g gulp
  - npm install -g gulp-cli
  - mkdir -p src/views/css
  - cp -R node_modules/mapbox-gl/dist/mapbox-gl.css src/views/css
  - cp -R node_modules/mapbox-gl/dist/mapbox-gl.js src/views/js

before_script:
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - sudo sed -i "172,\$s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf
  - sudo service apache2 restart
  - mysql -u root -e "CREATE USER 'dbadmin'@'localhost' IDENTIFIED BY 'dbpass'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'dbadmin'@'localhost' WITH GRANT OPTION;"
  - sudo chown -R travis:travis /var/www/html
  - bash factory/common/install-ps.sh $PS_VERSION $PS_MULTISITE
  - bash factory/common/sync.sh
  - bash factory/common/test/build.sh $PS_VERSION $PS_MULTISITE true
  - bash factory/travis/travis.sh $RUN_CODE_COVERAGE
  - if [[ -d /var/www/html/config/themes/classic ]]; then sudo chmod 777 -R /var/www/html/config/themes/classic; fi

script:
  - phpunit -c /var/www/html/phpunit.xml -v --debug
  - if [[ $RUN_PHPCS = "1" ]]; then bash factory/common/phpcs.sh true; fi

after_script:
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar; fi
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then chmod +x php-coveralls.phar; fi
  - if [[ -f /tmp/coverage.xml ]]; then sudo chmod 777 /tmp/coverage.xml; fi
  - if [[ $RUN_CODE_COVERAGE == 1 ]]; then php php-coveralls.phar -c /home/travis/build/Boxtale/boxtal-connect-prestashop/.coveralls.yml -x /tmp/coverage.xml --verbose -r /var/www/html/modules/boxtalconnect; fi
  - ls -al /home/travis/build/Boxtale/boxtal-connect-prestashop

sudo: required
